# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- cj

pool:
  self-hosted

variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)  
  REPO_NAME: $(Build.Repository.Name)
  REF: $(Build.SourceBranch)
  GHES: "https://dhruvg20-1685690800.gh-quality.net"
  #UPLOAD_TOKEN: $(UPLOAD_TOKEN_SEC)


steps:

- script: |
    echo $(GIT_COMMIT)
    echo $(GIT_BRANCH)
    echo $(REPO_NAME)
    echo $(REF)
    echo $(GHES)
    #echo $UPLOAD_TOKEN    
  displayName: 'Build variables'
  #env:
    #UPLOAD_TOKEN: $(UPLOAD_TOKEN_SEC)


- task: UseDotNet@2
  inputs:
    version: '7.0.x'

- script: |
    dir
    msbuild -target:clean
  displayName: 'dotnet build'

- script: dotnet --version
  displayName: 'Dotnet'


- script: |
    dir
    codeql database create WebGoatNet --language=csharp --command="msbuild"
    #./codeql database create WebGoatNet -l csharp --command="msbuild"
  displayName: 'Creating CodeQL DB'

- script: |
    codeql resolve languages
    codeql resolve qlpacks
    #./codeql/codeql pack install /home/vsts/work/1/s/codeql/csharp
    codeql database analyze WebGoatNet --format=sarif-latest --output=results.sarif
  displayName: 'Analyze CodeQL DB'