# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- cj

pool:
  self-hosted

steps:

- task: UseDotNet@2
  inputs:
    version: '7.0.x'

- script: msbuild -target:clean
  displayName: 'Dotnet Build stage'

- script: dotnet --version
  displayName: 'Dotnet'


- script: |
    dir
    codeql database create WebGoatNet --language=csharp --command="msbuild"
  displayName: 'Creating CodeQL DB'

- script: |
    codeql resolve languages
    codeql resolve qlpacks
    #./codeql/codeql pack install /home/vsts/work/1/s/codeql/csharp
    codeql database analyze WebGoatNet --format=sarif-latest --output=results.sarif
  displayName: 'Analyze CodeQL DB'


- script: |
   echo $(GITHUB_TOKEN) | codeql github upload-results --repository=$(Build.Repository.Name) --ref=$(Build.SourceBranch) --commit=$(Build.SourceVersion) --sarif=results.sarif --github-auth-stdin
  displayName: 'Upload SARIF File to GitHub'
